version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - mongo-data:/data/db
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - mongodb
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb
volumes:
  mongo-data:
    driver: local
