export const MENU_HANDLER = 'MENU_HANDLER';
export const AUTH_HANDLER = 'AUTH_HANDLER';
export const REGISTRATION_HANDLER = 'REGISTERATION_HANDLER';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AVATAR = 'AVATAR';
export const CREATE_AUDIO = 'CREATE_AUDIO';
export const RESET_AUDIO = 'RESET_AUDIO';